# Based on https://github.com/TrafeX/docker-php-nginx/blob/master/config/conf.d/default.conf
# and https://getkirby.com/docs/cookbook/development-deployment/nginx
server {
    listen [::]:8080 default_server;
    listen 8080 default_server;
    server_name localhost;

    root /var/www/html;
    index index.php index.html;

    default_type text/plain;
    add_header X-Content-Type-Options nosniff;

    rewrite ^/(data|site|kirby)/(.*)$ /404 last;
    rewrite /\.(?!well-known/) /404 last;
    rewrite ^/(?!app\.webmanifest|50x\.html|404\.html)[^/]+$ /index.php last;

    error_log /var/www/html/data/error.log error;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php-fpm.sock;
        fastcgi_intercept_errors on;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param APP_URL ${APP_URL};
        fastcgi_index index.php;
        include fastcgi_params;

        if ($request_uri !~ ^/panel) {
            error_page 500 502 503 504 /50x.html;
            error_page 404 /404.html;
        }
    }
}